name: Test code
on: push
jobs:
    test-job:
        runs-on: ubuntu-latest
        steps: 
          - name: Get code
            uses: actions/checkout@v4.1.1
          - name: Setup .NET Core SDK
            uses: actions/setup-dotnet@v4.0.0
            with: 
               dotnet-version: '8'